spring:
  h2:
    console:
      enabled: true
      path: '/console'
  jpa:
    hibernate:
      ddl-auto: validate
  #    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb #utworzenie bazy danych H2 w pamieci z adresem testdb




# logowanie zapytan sql
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
